- docs/Installing/overview.md
- sidebars.js
Pre Requisites & Unsupported services
> Installation Overview

- docs/Installing/overview.md
I've added some details to address issue #26
> Update overview page

- docs/Installing/Local/your-own-machine.md
- sidebars.js
> Local Install Docs

- docs/Developers/ActualQL/Examples.md
- docs/Developers/ActualQL/Functions.md
- docs/Developers/ActualQL/Overview.md
- docs/Developers/Building-Windows.md
- sidebars.js
Examples on how to use ActualQL and a re-arrangement of the sidebar, this resolves #16
> ActualQL Examples

- docs/Budgeting/categories.md
> Category Document Flow

- docs/Budgeting/schedules.md
I've added a section to discuss the two day window for scheduling transactions.
> scheduling window of 2 days

- docs/Getting-Started/sync.md
I added a section for end to end encryption.  This is mostly copy and paste from actualbudget.com with a few additions and clarifications.  Reference PR https://github.com/actualbudget/actual/pull/265
> e2e encryption sections

- docs/Installing/Terraform.md
link to 'Deploying Actual on fly.io with terraform' page
> Update Terraform.md: add link to 'Deploying Actual on fly.io with terraform' page

- docs/Getting-Started/sync.md
I’d love any feedback you might have on this! Fixes #6, unblocks https://github.com/actualbudget/actual/pull/265
The “migrating from older versions” section has been removed for now because it is no longer relevant (files from v120 can’t be used with the open source version)
> Add some documentation for the end-to-end encryption system

- docs/Getting-Started/migration/nynab.md
- sidebars.js
I've copied the instructions from https://github.com/actualbudget/actual/tree/master/packages/import-ynab5 to be included in the documentation.
I have not tested these instructions and assume they are accurate.
> nYnab export instructions

- docs/Developers/types.js
- docs/Developers/using-the-API.md
- Fix the instructions to no longer reference `runWithBudget`
- Incorporate the changes from https://github.com/actualbudget/actual/pull/464
> Update the API docs

- docs/Budgeting/rules/rules-custom.md
- docs/Installing/fly/Fly-image.md
- docs/Installing/fly/Fly.io.md
> update discord links

- docs/Troubleshooting/SharedArrayBuffer.md
- sidebars.js
Ref: https://github.com/actualbudget/actual/issues/511
> Add docs for the SharedArrayBuffer issue

- docs/Accounts/Transactions/importing-trans.md
- docs/Getting-Started/using-actual/accounts.md
- docs/Getting-Started/using-actual/overview.md
- docs/Getting-Started/using-actual/settings.md
Just some small typos I saw while getting actual set up for the first time.
I didn't see a `CONTRIBUTING.md` in this repo, so I apologize in advance if I missed any rules about opening PRs
> Fix minor typos in documentation

- sidebars.js
Removing some of the non Actual based installation methods
> Removing some of the non Actual based installation methods

- docs/Installing/Configuration.md
- docs/Installing/HTTPS.md
- docs/Troubleshooting/SharedArrayBuffer.md
- sidebars.js
Related: https://github.com/actualbudget/actual/pull/648
> Move HTTPS docs to a separate file and add more information

- docs/Developers/releasing.md
Added a paragraph about the new versioning strategy we plan to adopt starting from `v23.3.x`.
Let me know your thoughts.
> Versioning strategy

- README.md
- docs/Installing/overview.md
Adding the ability to have additional installation methods in the documentation linked to from external blogs etc.
> Installation Methods

- docs/Accounts/reconcile.md
> Typo: Changed band to bank

- docs/Installing/Docker.md
- docs/Installing/fly/Fly-image.md
...away from `jlongster`'s personal account. We're officially an org now!
Before merging,
1. merge https://github.com/actualbudget/actual-server/pull/175
2. build and push a new image to the org repo via `actual-server` CI
> Update all Docker Hub references to new actualbudget organization 

- docs/Getting-Started/using-actual/index.md
- docs/Release-Notes.md
**Actual has now been moved to a stand-alone Docker organization. If you were previously using `jlongster/actual-server` docker image - please update it to `actualbudget/actual-server`.**
The release has the following notable features:
- Rules can now optionally be applied when any of their conditions match (in addition to the existing option to apply when all of their conditions match)
- Rules: quick-create option from the transaction table (in the “X selected” menu that shows up after selecting a transaction, choose “Create rule”)
- Ability to hide decimal places for currencies with large numbers (in Settings → Formatting)
- New autocomplete component (please report any bugs [here](https://github.com/actualbudget/actual/issues/773))
- Lots of smaller improvements and bugfixes
> :bookmark: (23.4.0) release notes

- docs/Release-Notes.md
- web: https://github.com/actualbudget/actual/pull/930
- server: https://github.com/actualbudget/actual-server/pull/192
> :bookmark: (23.4.2) revert back to old autocomplete & keyboard shortcut fix

- docs/Advanced/Experimental-Features/goal-templates.md
> Fix table in goal template docs

- docs/Advanced/Experimental-Features/goal-templates.md
Info about using PR#1004 of base app.
> Add info on template hold flag

- docs/install/fly.md
I meant to come back and fill this in as part of #127 but forgot about it — @rich-howell does this instruction sound correct?
> Fix cd instructions for Windows

- README.md
- docs/api/types.js
- fix broken issue link
- tweak the typography in the API docs
> A few minor updates

- .editorconfig
- src/pages/index.js
Updated the tagline (the hook) for the website.
For people coming in for the first time - they don't know (and care) about the historical context of open source actual vs closed source. So slightly changed the copy to focus on the truly important things - the features.
> :pencil:  updating the website tagline, the hook

- docs/api/reference.md
ref: https://discord.com/channels/937901803608096828/1122664924582260786/1123052436219760691
> Fix errors in import example

- docs/backup-restore/restore.md
The heading layout was a little wonky & wanted to correct some info about backup availability
> Update the restore doc

- docs/experimental/goal-templates.md
matches [actualbudget/actual#1254](https://github.com/actualbudget/actual/pull/1254)
I also did some minor cleanup and fixed a wrong statement I added previously.
> Entry for available funds percent goal

- blog/2023-07-04-release-23.7.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/1280
- server: https://github.com/actualbudget/actual-server/pull/222
- docs: https://github.com/actualbudget/docs/pull/223
> [WIP] :bookmark: (23.7.0) Nordigen release, stability improvements

- blog/2023-07-05-release-23.7.1.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/1295
- server: https://github.com/actualbudget/actual-server/pull/224
- docs: https://github.com/actualbudget/docs/pull/225
> :bookmark: (23.7.1) critical sync fixes

- docs/backup-restore/restore.md
updated `restore.md` to include instructions on manual db updates
> instructions on manual db updates

- blog/2023-07-09-release-23.7.2.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/1322
- server: https://github.com/actualbudget/actual-server/pull/225
- docs: https://github.com/actualbudget/docs/pull/230
> :bookmark: (23.7.2) more patches (not so critical, but still annoying)

- docs/accounts/index.md
Minor edit to text and link added to the correct page in Docs re Nordigen bank sync
> New Account - Add link to Bank Sync Notes

- docs/install/docker.md
This will put 'Update' in the Index on the right side of the Docker page to help people discover how to update Docker images.
> Add 'update' subheadings for docker

- docs/budgeting/rules/index.md
Update Docs re mechanics to delete Rules
> Update Docs re delete Rules

- docs/tour/index.md
Part of these instructions referred to desktop app and are now amended
> A tour of actual - small update

- docs/tour/settings.md
A partial update to the text until the screenshots can be updated
> Describe how to access "Settings"

- docs/experimental/goal-templates.md
Matches [#1403](https://github.com/actualbudget/actual/pull/1403)
Tweaked some things that I noticed that were confusing.
> Goals: add blurb for previous flag, clean up confusing note

- .github/actions/spelling/expect.txt
- blog/2023-07-09-release-23.8.0.md
- docs/releases.md
- docs/tour/settings.md
- web: https://github.com/actualbudget/actual/pull/1444
- server: https://github.com/actualbudget/actual-server/pull/238
- docs: https://github.com/actualbudget/docs/pull/257
> :bookmark: (23.8.0) stability improvements and new experimental features

- docusaurus.config.js
Fixes the link used in `/blog/rss.xml`
> Fix docs link

- .github/actions/spelling/expect.txt
- blog/2023-07-09-release-23.8.0.md
- blog/2023-07-09-release-23.8.1.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/1475
- server: https://github.com/actualbudget/actual-server/pull/240
- docs: https://github.com/actualbudget/docs/pull/260
> :bookmark: (23.8.1) fix nYNAB import, mobile colors and other smaller fixes

- docs-sidebar.js
- docs/contributing/leadership/new-core-contributors-guide.md
New Core Contributor Guide
Information that is useful to know when joining the team.
> :pencil:  new core contributor guide

- blog/2023-10-03-release-23.11.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/1859
- server: https://github.com/actualbudget/actual-server/pull/273
- docs: https://github.com/actualbudget/docs/pull/274
> :bookmark: (23.11.0)

- docs-sidebar.js
The purpose is to move Contributor section to the end of the Docs. Currently it appears too early and creates too much clutter for new users
> Update Contributor Section - Side Bar Order

- blog/2024-01-06-release-24.1.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/2177
- server: https://github.com/actualbudget/actual-server/pull/295
- docs: https://github.com/actualbudget/docs/pull/299
> :bookmark: (24.1.0) Mobile split transactions

- docs/privacy-policy.md
- docusaurus.config.js
Necessary for submitting to Mac App Store.
> :pencil: created privacy policy

- docs/community-repos.md
> add moneymoney importer

- docs/budgeting/categories.md
- docs/budgeting/index.md
- docs/getting-started/starting-clean.md
- src/pages/index.js
mostly some more detailed advice in the starting fresh doc.  Im trying to make the budgeting advice be more centralized instead of being in random places
A few minor tweaks
A few call outs that simplefin is not just a community thing anymore
> update starting fresh doc, and add simpleFIN call outs

- docs/config/https.md
Sounds like I'm not the only one that has run into this issue 😄
> Add final step to enabling https on home server

- .github/actions/spelling/allow/keywords.txt
- blog/2024-02-06-release-24.3.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/2413
- server: https://github.com/actualbudget/actual-server/pull/317
- docs: https://github.com/actualbudget/docs/pull/327
> :bookmark: (24.3.0)

- docs/experimental/monthly-cleanup.md
[#2409](https://github.com/actualbudget/actual/pull/2409)
> Rollover notes: Update for PR 2409

- docs/api/index.md
Added clarity about migrating from YNAB or Mint to Actual. 
Corrected grammatical error about what Actual officially supports for importing from other budgeting apps.
> Update index.md - "Using the API"

- docs/community-repos.md
Links to this custom importer in the community page
> add financier migration repo

- docs/faq.md
As the title says, update the response of the FAQ indicating the mobile web layout
> Update the FAQ to reflect the new mobile layout feature

- docs/tour/index.md
Fixing a double dot in the tour
> Remove double dot in tour

- docs/experimental/monthly-cleanup.md
I think there is a better example than the one I've proposed here.  I'm not convinced the example I've given would even provide an expected result to the user.  I'd appreciate any feedback of those interested and the PR #2480 could be improved to deliver more expected results.
> Cleanup documentation for local groups

- docs/community-repos.md
[Shared](https://discord.com/channels/937901803608096828/940290142579605514/1227116311935582260) the app I developed in Discord and was [advised](https://discord.com/channels/937901803608096828/940290142579605514/1227331697700376586) to add to the Community Repos page.
> Update community-repos.md with Actual Tap

- docs/experimental/goal-templates.md
matches actualbudget/actual#2688
> add line for average template

- .github/actions/spelling/allow/keywords.txt
- blog/2024-05-03-release-24.5.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/2693
- server: https://github.com/actualbudget/actual-server/pull/351
- docs: https://github.com/actualbudget/docs/pull/352
> :bookmark: (24.5.0) mobile improvements and much more

- docs/api/reference.md
Implementation: https://github.com/actualbudget/actual/pull/2683
> :sparkles: (api) ability to run bank sync via the API

- docs/index.md
This updates the home page documentation with some content enhancement as per the style guide (mainly MSTP, Google Developer Style Guide). 
Based on the feedback, i will further add more section to enhance the home page to make it like a home for all the documentation for easier navigation.
For now, this PR kepts the section that are necessary to address user's query regarding getting started with Actual and understanding the Actual's starter kit.
> Home page documentation enhancement

- docs-sidebar.js
> Add reset password doc to the sidebar

- .github/actions/spelling/expect.txt
- blog/2024-06-03-release-24.6.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/2819
- server: https://github.com/actualbudget/actual-server/pull/368
- docs: https://github.com/actualbudget/docs/pull/360
> :bookmark: (24.6.0)

- docs/contributing/releasing.md
See more details here: https://github.com/actualbudget/actual/pull/2852
> :pencil: update release instructions

- docs/community-repos.md
Adds a link to my helper script repository
> Add link for helpers

- docs/api/index.md
- docs/api/reference.md
- docs/api/types.js
This adds missing documentation for existing API calls and removes one that does not exist.
> Add missing API documentation.

- docs-sidebar.js
- docs/reports-filters/custom-reports.md
- docs/reports-filters/index.md
- docs/reports-filters/reports.md
- src/pages/index.js
Update the custom reports page and move it out of experimental.  Misc other tweaks to be consistent about reports.
> custom reports no longer experimental

- .github/actions/spelling/allow/keywords.txt
- blog/2024-07-02-release-24.7.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/2955
- server: https://github.com/actualbudget/actual-server/pull/383
- docs: https://github.com/actualbudget/docs/pull/379
> :bookmark: (24.7.0) custom reports, splits in rules, tags and more

- docs/faq.md
- docs/install/index.md
from the docs on bank sync specifically, include best practices notes in the FAQ to recommend limiting past transactions
Fixes #363
> update bank sync faq question - add best practices

- docs/install/fly.md
add command about exactly how to redeploy the latest image under update. thanks @hippalectryon-0
fixes #384
> Add Command to update Fly instance via hippalectryon-0

- docs-sidebar.js
- docs/advanced/restart.md
Fixes #362 
Taken from Teprifer#muddledjellyfish's answer on Discord server.
> Create section on restarting your budget without removing transactions

- docs-sidebar.js
- docs/budgeting/envelope-budgeting.md
- docs/budgeting/index.md
- docs/getting-started/envelope-budgeting.md
I have added this page because I think the software used for envelope budgeting should definitively have some documentation on how to actually do envelope budgeting.
> Created page on the topic - How envelope budgeting works

- .github/actions/spelling/allow/keywords.txt
- docs/community-repos.md
- Added links to the My Edenred Portal bank sync and Actual Task repos.
- Moved some links from Others into Various utilities to enhance Actual's functionality, as I expect we will get more and more of these utilities available. Let's keep Other for pure non-functional technical stuff
Original posting: https://discord.com/channels/937901803608096828/1027831756545609789/1260289369139580988
I did source GitHub for other interesting projects and have added those also.
> Added various links to the Community Projects page

- docs/api/reference.md
- docs/api/types.js
API docs for https://github.com/actualbudget/actual/pull/2928.
> Add API docs for getLocalbudgets() and getRemoteBudgets().

- docs/api/reference.md
Docs for https://github.com/actualbudget/actual/pull/2930.
> Add getAccountBalance() API documentation

- docs/api/reference.md
- docs/contributing/index.md
Removing some outdated information. The API package has been available for a while already.
> 📝 update the API docs information

- docs/reports-filters/custom-reports.md
correcting typo from "reports available" to "reports are available"
> Update custom-reports.md for typo

- docs/tour/reports.md
typo from "two built in report" to "two built in reports"
> Update reports.md to fix typo

- docs/tour/budget.md
Changed text accordingly to menu item's title.
> [WIP] Fix typo in the budget.md

- docs/budgeting/rules/index.md
many people may not know what 'regex' is. now matches filters page. not sure why i didn't update both places when i got the review last time, sorry!
> update rules page w/ link to regex tutorial

- README.md
- docs-sidebar.js
- docs/contributing/i18n.md
Initial draft for contribution guidelines on how to prepare Actual for i18n and l10n.
Please do add your feedback!
> Add i18n documentation

- docs/contributing/releasing.md
> Adding instructions for the windows store release

- docs/api/reference.md
Clarify that `importTransactions` runs rules
> [WIP] Clarify post-processing in `add/importTransactions`

- docs/community-repos.md
> Add note about new #community-projects Discord channel.

- .github/actions/spelling/allow/keywords.txt
- blog/2024-09-03-release-24.9.0.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/3348
- server: https://github.com/actualbudget/actual-server/pull/444
- docs: https://github.com/actualbudget/docs/pull/444
> :bookmark: (24.9.0)

- docs/install/pikapods.md
Added information on how Pikapods updates for each monthly release, including how this works with desktop clients.
> Added info on how Pikapods updates

- .github/actions/spelling/allow/keywords.txt
- docs/config/https.md
Notes on mkcert when used with desktop app. 
Should resolve future questions like this one: https://discord.com/channels/937901803608096828/1281484103580909621/1284432537682317365
> Update notes on self signed certificates for desktop app

- docs/community-repos.md
remove simplefin community tool because simplefin has been integrated officially
> Update community-repos.md to remove simplefin community in favor of official simplefin integration

- docs/migration/ynab4.md
Added in a Known issues section for YNAB4 imports to cover an issue with split transactions not receiving correct payee details.
Once this issue is resolved the documentation note can be removed:
https://github.com/actualbudget/actual/issues/3561
> [WIP] Update ynab4.md

- docs/settings/index.md
As of 24.10.0, simplefin is not in experimental features anymore, and now there is a customizable reports option.
> Update advanced settings in index.md

- blog/2024-10-08-release-24.10.1.md
- docs/releases.md
- web: https://github.com/actualbudget/actual/pull/3596
- server: https://github.com/actualbudget/actual-server/pull/475
- docs: https://github.com/actualbudget/docs/pull/465
> :bookmark: (24.10.1)

- docs/experimental/goal-templates.md
add blurb for the new copy template from actualbudget/actual#3617
> add copy template

- docs/contributing/preview-builds.md
add mention of how to access the edge build of actual, i couldn't find it anywhere else in the documentation.
> Add info on how to access edge build via edge.actualbudget

- docs/tour/accounts.md
the arrows are the yellow box not blue.
> incorrect box specified from the photo

- docs/tour/index.md
> [WIP] Update index.md

- docs/api/actual-ql/functions.md
This adds an example to show how to change the sort order.
> Add example of orderBy with a descending order

- docs/getting-started/envelope-budgeting.md
4 was duplicated, changed second occurrence to 5.
> [WIP] fix envelope budgeting numbering typo

- blog/2025-01-02-roadmap-for-2025.md
Recounting my journey from YNAB to Actual. Giving a brief roadmap for 2025. And lastly answering some comments/questions I keep seeing on the internet.
https://deploy-preview-588.www.actualbudget.org/blog/roadmap-for-2025
> :pencil: (op-ed) looking ahead to 2025

- docs/contributing/releasing.md
Goes with https://github.com/actualbudget/actual/pull/4105
> Update releasing.md for release notes

- docs/getting-started/envelope-budgeting.md
> [WIP] Update envelope-budgeting.md

- docs/faq.md
> [WIP] Update faq.md

- .github/actions/spelling/expect.txt
- docs/community-repos.md
Hello, 
I've created a prometheus metrics exporter and want to share it with a community :)
> Add actual-budget-prometheus-exporter

- docs/releases.md
Closes https://github.com/actualbudget/docs/issues/493
> add release dates to releases page

- .github/actions/spelling/expect.txt
- docs/experimental/goal-templates.md
Goes with https://github.com/actualbudget/actual/pull/4257
> Documenting percentage adjustments feature for actual PR #4257

- docs/transactions/filters.md
s/To clear out the any/To clear out any/
> [WIP] Small grammar correction to filters docs page

- docs/getting-started/starting-fresh.md
s/like bill and groceries/like bills and groceries/
> Grammar correction to starting-fresh.md page

- docs/config/index.md
- s/want to Actual to serve/want Actual to serve/
- s/allowed to authentic with/allowed to authenticate with/
> Two small corrections to config docs page

- docs/accounts/index.md
Replace: Link to GoCardless
With: Link (to GoCardless for Eurpean Banks or SimpleFin for North American Banks)
> Add SimpleFIN where GoCardless mentioned in Accounts docs

- blog/2025-03-03-release-25-3-1.md
- docs/releases.md
https://github.com/actualbudget/actual/pull/4497
> 🔖 (25.3.1)

- docs/config/index.md
> Add missing doc about env vars.

- docs/budgeting/rules/index.md
Added instructions to the rules documentation for disabling future automatic rule creation.
> Added instructions for disabling automatic rule creation

- docs/community-repos.md
PR to add a link to a tool to auto-sync accounts on a schedule.
https://github.com/seriouslag/actual-auto-sync
> [WIP] Update community-repos.md to add actual-auto-sync

- docs/actual-server-repo-move.md
Put Windows-specific step in parens to differentiate it from the rest of the steps
Also gave clarification upfront to inform users what the end-goal is.
> [WIP] Update actual-server-repo-move.md

- docs/experimental/pluggyai.md
Adding required step to enable Pluggy under current version
> [WIP] Update pluggyai.md - Adding missing required setting step

- .github/actions/spelling/expect.txt
- blog/2025-05-03-release-25-5-0.md
- docs/releases.md
code: https://github.com/actualbudget/actual/pull/4916
> 🔖 (25.5.0)

- docs/install/index.md
See https://discord.com/channels/937901803608096828/1027831463103696928/1349820333221478431.
Ordered the list alphabetically.
> Add link til Arch Linux User Repository (AUR) package 

- .github/actions/spelling/expect.txt
- docs/community-repos.md
PR to add a link to a collection of userscripts to use with Actual web client.
https://github.com/pogman-code/actual-userscripts
> Update community-repos.md to add actual-userscripts

- docs/getting-started/envelope-budgeting.md
> Fixing miscalculation

- .github/actions/spelling/expect.txt
- docs/install/index.md
There was one package in the doc (actual-appimage) but there is more actually :D  
2 Desktop clients based on the AppImage and a server based on the @actual-app/sync-server NPM package.
> List Arch AUR packages

- docs-sidebar.js
- docs/install/apple-container.md
Adds documentation to run Actual in the newly released Apple Containers.
> apple container docs

- docs/contributing/writing-docs.md
We use warnings several places, especially with regards to experimental features.
> Added Warning callout as this was missing

- .github/actions/spelling/expect.txt
- blog/2025-07-01-release-25-7-0.md
- docs/releases.md
https://github.com/actualbudget/actual/pull/5260
> 🔖 (25.7.0)

- docs/getting-started/tips-tricks.md
Documentation updates related to https://github.com/actualbudget/actual/pull/5330
> add new shortcut key references

- docs/community-repos.md
found this importer named Moneyman,
It can import from most banks in Israel 
see
https://github.com/daniel-hauser/moneyman
> [WIP] add a link to new importer

- .github/actions/spelling/expect.txt
- blog/2025-08-01-release-25-8-0.md
- docs/releases.md
Actual PR: https://github.com/actualbudget/actual/pull/5447
> 🔖 (25.8.0)

- src/pages/download.md
> Download page is now centered.

- docs/backup-restore/restore.md
Completed the beginning introduction of Restoring a Backup doc
**P.S. The first screenshot illustrating where to close the finance file needs to be updated to comply with that in the current version.**
> [WIP] Update restore.md

- docs/reports/index.md
Updated text widget description since it does not actually run or generate a report.
> Update text widget description in index.md
