actualbudget/docs

docs/Developers/releasing.md, docs/Installing/overview.md, sidebars.js
Migrating documentation from https://github.com/actualbudget/actual/blob/master/docs/releasing.md, this resolves #22
=> Releasing docs

docs/Release-Notes/Release-Notes.md
I've update the release notes regarding the recent update.  Here is a summary.
1) Added some notes for the release page regarding the Docker tags and warning about the 22.12.3 and 22.12.8 tags.  
2) Highlighted the icon change in the features list
3) Added the final published docker tag for each of the releases.
=> Update release notes regarding 22.12.03

docs/Installing/Configuration.md, docs/Installing/overview.md, docs/Troubleshooting/SharedArrayBuffer.md, sidebars.js
HTTPS support will only be available after the next release of Actual, so it may make sense to wait to merge this until the release happens.
=> Add docs for the config file and HTTPS

docs/Release-Notes.md
This fixes a couple of typos and makes the source code easier to read. In the future, add the GitHub URLs for new contributors to the reference section at the bottom of the document, and then just use `[username]` to make the link in the main content. Revival of #92.
=> Convert user mentions to reference-style links in the release notes

docs/Installing/Configuration.md
- Add `ACTUAL_CONFIG_PATH`
- add env variable equivalents to all settings
- add `webRoot`/`ACTUAL_WEB_ROOT`
- not recent, but mention that creating `/data` will move the default data storage there
(note: this describes the changes in https://github.com/actualbudget/actual-server/pull/127, so it might be good to wait to merge this until that is merged)
=> Update config docs for recent improvements

docs/Installing/Unraid.md
Updates and cleans up a few other things too.  I don't personally use CA, so added a few details for those who wish to setup without using it.
=> Update Unraid docs with steps to generate certificates 

docs/Getting-Started/migration/migration-intro.md, docs/Installing/overview.md
closes #25 
It can be confusing for users of the old hosted Actual who want to migrate to the new self-hosted version, because the old Desktop app doesn't have the export button.
This PR adds a note to the Migration page about using the Web version which does have the export button, and links to it from the Installation overview.
=> Add note on migration from old version

docs/Budgeting/returnsandreimbursements.md, docs/Installing/fly/Fly-git.md, docs/Installing/fly/Fly-prerequisites.md, docusaurus.config.js, package-lock.json, package.json, src/components/Image.jsx, src/remark/rewrite-images.js, src/theme/MDXComponents.js
This PR adds the Docusaurus image plugin, which adds functionality like processing images (which we don’t heavily use at this point), creating a blurred thumbnail for display before the image loads, and computing image size at build time so the page can be laid out properly right away.
I’ve also written a Remark transform to convert `![](...)`-style images to the format needed to get the metadata to work correctly.
Finally, I’ve added support for Retina screenshots — if you name an image with `@2x` it will automatically have its preferred size halved to ensure it shows up right.
=> Add an image handling component

docs/Installing/HTTPS.md
Based on the code, the paths are no longer `keyPath` and `certPath`. This errors when using the config.json file.
The server looks for `key` and `cert`:
```
key: parseHTTPSConfig(config.https.key),
cert: parseHTTPSConfig(config.https.cert)
```
https://github.com/actualbudget/actual-server/blob/master/src/app.js#L66-L67
=> Update HTTPS certs when using config.json

docs/Developers/releasing.md
Updating release instructions. The current instructions were slightly outdated.
=> :pencil:  update release instructions

docs/Installing/Configuration.md
These showed up in the rendered docs:
=> Remove backticks in config.json example

docs/Installing/Docker.md
Based on testing and discussion in Discord, the `edge` tag does contain the latest `desktop-client` as well. Removes an outdated statement in the Docker install documentation that stated otherwise.
=> edge tag contains latest server and client

docs/Developers/releasing.md
This allows people to subscribe to the RSS feed at https://github.com/actualbudget/actual/releases or subscribe for release-only notifications on the repo.
=> Add step to create a GitHub release when publishing a release

docs/Installing/fly/Fly-image.md
making it clearer to run `fly launch` from the specific directory where `fly.toml` is located as per issue #140
=> fly launch cd clarification - resolves #140

docs/Advanced/Experimental-Features/goal-templates.md
This adds basic documentation for using the 'schedule' keyword in https://github.com/actualbudget/actual/pull/885.
=> Goals:  Added 'schedule' keyword to syntax chart

docs/Getting-Started/tipstricks.md
I added some non documented keyboard shortcuts for the transaction ledger.  I also standardized the capitalization of the existing shortcuts.
I cant decide if its better to have the single letters upper or lower case.  I don't want to imply that a `Shift` press is needed.  Also, in `Ctrl + o` shortcut, the  `o` was lower case maybe to try and not look like the number.  I don't think I have a preference and can change it to upper case if that is preferred.
=> Additions to keyboard shortcuts

docs/Installing/fly/Fly-updating.md
I have a suggestion for the "Updating Actual" doc page. Since fly.toml is in .gitignore pulling changes via git won't update it. Users should also update their fly.toml before deploying on server. 
I added short info in the Fly-updating.md. However I don't know if this info should also be updated elsewhere.
=> Update Fly-updating.md- Add info about updating fly.toml before deployment

docs-sidebar.js, docs/contributing/index.md, docs/contributing/project-details/database.md, docs/contributing/project-details/index.md
- Moved 'The Actual Project Structure' into its own subfolder
- Added a page detailing some info about the database structure of actual
- Removed the reference to 'loot-design' as I think this no longer exists.
=> Updating project information docs

docs/install/index.md
Home Assistant is an open source home automation framework commonly installed on Raspberry Pi devices as an open source home automation controller.
It has an extensive Add-On package manager allowing people to install various extensions. Actual Budget's architexture makes it a good candidate as an add-on:
* Add-ons are mainly single docker containers, and actual can already run as a single docker container
* It only needs access to `/data` and a single http port to run - ideal condition for HA Add-Ons
* The server is actually only used for syncing, calculations and computational intensive features run on the client machines, so running it would not take away too much resources on limited machines, like the RPi commony used as a HA box
I have made an Add-On repository for Home Assistant …
=> Add Home Assistant as a community install option

static/_redirects
This ensures that old links won’t break.
=> Add redirects for all pages on the old actualbudget.com

docs/reports-filters/filters.md
Added a note regarding the dropdown arrow by "Date" and "Amount"s in view of a recent bug report that showed that these are not always easily discovered..
PS Sorry to keep adding changes but I am trying to respond quickly to @shall0pass comments on another issue
=> Explanation of Filter Dropdowns

docs/contributing/index.md
The markup of the release notes template in the contributing docs accidentally have the ending tag for the code block located before the actual example release notes message.
=> Fix markup of release note template for contributing docs

docs/budgeting/index.md
I believe this was incorrect, as skipping step 6 would mean there isn't anything put into the savings category.
=> Fix step to skip if no savings account.

docs/api/index.md
So they point to existing implementations. The current links are broken and Im hoping these links are correct - someone please let me know if this is incorrect, thanks
=> Update ynab4 + 5 importer links in api docs

docs/api/reference.md
To match changes from https://github.com/actualbudget/actual/pull/1944
=> API update learnCategory,runTransfers for addTransactions

.github/actions/spelling/allow/keywords.txt, docs-sidebar.js, docs/accounts/index.md, docs/getting-started/starting-clean.md
Depends on #278.
Fixes #251
This adds a dedicated guide for those that are starting fresh with Actual and aren't familiar with zero-sum budgeting.  It is a step by step that points to the existing pertinent docs pages with additional direction.
=> guide for starting fresh

docs/migration/nynab.md
When importing from nYNAB `to budget` doesn't match the previous `ready to assign` value.  I added a description of why that is and how to make the numbers match.
=> add info about aligning to_budget on nynab import

docs/transactions/transfers.md
We get lots of questions about transfers involving off budget accounts.  This will hopefully alleviate some of that confusion.
It was mentioned in [actualbudget/#1979](https://github.com/actualbudget/actual/issues/1979) that the docs don't have a good description of this.
=> blurb about transfer categories

docs/api/index.md
Related to https://github.com/actualbudget/actual/issues/1695
It's pretty common for users to have self-signed certificates for actual, but this presents some challenges for the API.
Give a little bit of guidance here, for new contributors. Really, all the info here is just for Node.js and not for actual. (we would want to create seperate http agents and our own certificate config system if we wanted to have actual specific config for this).
For many of the existing api use-cases the `NODE_TLS_REJECT_UNAUTHORIZED` option will be fine. But `NODE_EXTRA_CA_CERTS` seems like the proper way to do things (and the one I tested on nodejs 21, on ubuntu via asdf install). But I also made sure to mention the option of using openssl's ca certificates, because if you are in a situation where your …
=> Add info on self-signed https connections from the API

docs/config/reverse-proxies.md
While deploying with Traefik I found two small errors in the documentation. 
First is the duplicate line, the second is the missing line so that Traefik knows on which port it should send the traffic to.
=> 📝 (reverse proxies) Remove duplicate line, add service port for Traefik

docs/install/fly.md
As discussed in [#296](https://github.com/actualbudget/docs/issues/296) the new
pricing structure of Fly is confusing and not being communicated well.
This PR puts up a temporary notice explaining this, so that new users are
informed and won't get slugged with an surprise $5 charge (if that is indeed the
case... 🤷).
It also offers a temporary solution to move ahead with a local install, which
can then be pushed to Fly later on. So new users won't just hit a dead end
either.
=> cautionary notice about new Fly pricing

docs/config/reverse-proxies.md
Moves the summary of NGINX section to the top to match the others. 
Added config section for Apache HTTPD.
=> match nginx with other formatting, add httpd

docs/experimental/goal-templates.md
The regex for the parser is implemented to match any currency symbol:
https://github.com/actualbudget/actual/blob/5a67b7e822eb6d10b1e661869b71083e0b4cc8f6/packages/loot-core/src/server/budget/goal-template.pegjs
=> Goal templates: Edit note that currency symbols other than $ are supported

docs/contributing/project-details/database.md
Incredibly minor change. I'm assuming this aligns to the brand template as I saw "Actual" (capitalized) elsewhere.
=> Capitalize "actual" on line 7

docs/experimental/goal-templates.md
My schedule templates weren't working because I was including the curly braces around the schedule name.
=> Clarify that goal schedule template should not include braces

docs/api/reference.md
Removed api methods that do not exist. Since they don't exist - they should not be in the docs.
It would be nice to implement them though.. but until they are implemented - lets not mislead people.
=> :fire: remove non-existing api methods from api docs

src/pages/index.js
Changes the Open Collective URL from `.org` to `.com` (the `.org` is not accessible).
=> fix: Open Collective link

docs/experimental/simplefin-sync.md
This adds simple instructions to manually reset the SimpleFIN setup token.
=> docs: Add instructions to reset SimpleFIN token.

docs/install/fly.md
fly.io pricing details have changed for new users. new users can only sign up for a pay-as-you-go plan where usage is billed monthly. as this is about deploying actual, it should be aimed at new users, not returning users with maybe-existing legacy plans(like the hobby plan) details about the legacy plans can still be found at the linked page.
=> fly.io new pricing details update

src/pages/index.js
some of the features on the homepage seemed there just to pad out the list.  The list if decently long and interesting so I removed Payees and Split transactions.  Those seem pretty expected and not that interesting as a called out feature.
I modified the budgeting feature to be more specific.  Just saying we have budgeting is a bit redundant for a budgeting app.
=> Clean up the homepage feature list

docs/experimental/simplefin-sync.md
Since https://github.com/actualbudget/actual/pull/2870 is being released, the docs should update to the new way to reset the token.
=> Update SimpleFIN reset instructions.

blog/2024-07-01-ynab_v_actual.md
since the link paths are treated differently depending on if the blog is directly linked to vs navigated to.  I believe these links will always work
=> fix links in the ynab blog

docs/community-repos.md
Adds the link to the Python library I wrote for actual called [actualpy](https://github.com/bvanelli/actualpy) to the list of community projects. It's also released [on Pip](https://pypi.org/project/actualpy/).
Library implements the core functionality of most of the original API, by a mix of reverse-engineering the UI calls and the checking the source code.
Experimental features cover bank syncs, schedules and rules.
=> Add reference to the Python library

docs/community-repos.md
The current Actual Tap repo is now archived and developement has been moved to a new repo
=> Move ActualTap to ActualTap-py

docs/install/index.md
Fly.io no longer offers free cloud hosting; it is pay as you go with actual usage billed monthly. I calculated between Pikapods $1.4 per month and Fly.io's $1.5 per month and chose Pikapods since it's one click and it's cheaper. If there's anything wrong in my calculations, please let me know.
=> Update fly.io pricing information

.github/actions/spelling/allow/keywords.txt, docs/community-repos.md
Added link to converter from Trumf Visa PDF invoice to Actual Budget friendly CSV import file.
=> Converts Norwegian Trumf Visa PDF invoice to an AB friendly CSV file

docs/advanced/bank-sync.md
1. Added information about the number of syncs on the free tier (which is 50).
2. Added link to documentation on how GoCardless counts connections.
3. Added alt-text to all images.
4. Fixed a typo in one of the numeration of the steps in how to link a GoCardless account to AB - step 8 was repeated twice.
=> [WIP] GoCardless clarification on number of requests on the free tier + alt-text of images + fix a step number

docs/api/index.md, docs/faq.md
We seem to be getting this question a lot lately. So now we should be able to just link people to the docs when they ask the question.. :)
=> :pencil: highlight that Actual does not have a HTTP API

src/pages/download.md
**Possible improvement for later:** we could detect the OS the user is using and filter the list down so there aren't so many options.
=> Update Mac links on Downloads page 

docs/advanced/bank-sync.md
This adds a note on the Advanced/Bank Sync page linking to the SimpleFIN page:
=> Make note/link about SimpleFIN in the bank docs page.

docs/contributing/i18n.md
Actual Budget does not use namespaces in the translations.
Also adds additional section about handling interpolation using the <Trans> component.
=> Remove namespace from i18n example

docs/advanced/bank-sync.md
Provides steps to contribute to the GoCardless list of banks with limited (90 day) historical data.
=> Add FAQ entry on how to add GoCardless bank to limited history list.

docs/community-repos.md
i've made a simple home assistant integration
https://github.com/jlvcm/ha-actualbudget
it allows me to use Home assistant to send the historic data to timescaleDB, access the balances through the assistant+chatgpt, and create alerts and graphs on Home assistant and grafana
i've done it in the last couple of days, so it's still on its first days, it's working but only has balances but it seems easy enough to add budgets and other data once i pick it up again
use it as you wish, and any contribution is welcome, if you need any help just let me know 🙏
=> Add actualbudget home assistant integration link

docs/install/docker.md
docker compose down is not needed, and running it before pulling updated images causes longer service downtime than required.
Simply running `docker compose up -d` after `docker compose pull` will recreate all containers that changed (by either image version or other settings in the compose file).
=> Remove compose down from update instructions

docs/install/index.md
Adding a section to install documentation that explains how one could use the web app for a quick start without sync.
=> Add web app install docs

docs/budgeting/rules/index.md
Some minor updates to the rules page to keep it in sync with the current UI:
- Updates the list of actions and fields so the order matches the UI.
- Adds missing `category` field to the list
- Mentions you can also append/prepend to `notes`
See: https://deploy-preview-463.www.actualbudget.org/docs/budgeting/rules/
=> Update rules page

blog/2024-11-03-release-24.11.0.md
As it says on the tin; noticed this was wrong while browsing the docs.
=> [WIP] Fix date on latest release post

docs/getting-started/tips-tricks.md
I was a little confused that I couldn't see a running balance in my accounts until I realized that it's only shown in a specific sort order. 
I think it would actually be useful to be able to see the running balance no matter the sorted order, but until then maybe we should clarify in the documentation.
=> docs: Explain running balance is shown only with descending date

blog/2024-12-05-release-24-12-0.md, docs/releases.md
As a consumer of these release notes it would be nice to have links to the documentation for new major features. I think it's especially helpful for Dashboards because the official feature name in the docs is called Reports (it seems to colloquially called Dashboards)
=> Add dashboard and tracking budget links to latest release notes

docs-sidebar.js
Closes https://github.com/actualbudget/docs/issues/585 
I'm guessing the original intention for the index page was for it to be associated with the Budgeting menu item.
=> [WIP] Closes #585

.github/actions/spelling/allow/keywords.txt, docs/community-repos.md
Also grouped this with with the Coinbase sync under a new heading called Other Importers, as they are not necessarily pure banking-related importers.
=> Adding Portuguese prepaid meal card tracking from @rodriguestiago0.

.github/actions/spelling/expect.txt, blog/2025-01-05-release-25-1-0.md, docs/releases.md
- web: actualbudget/actual#4095
- server: actualbudget/actual-server#536
- docs: #601
=> 🔖 (25.1.0)

docs/getting-started/tracking-budget.md
This PR updates the instructions for enabling Tracking Budget. The feature is no longer experimental, but the documentation still treats it as such.
=> Update instructions for enabling Tracking Budget

docs/community-repos.md
- https://github.com/IeuanK/AmazonExporter/
- https://github.com/IeuanK/ICS-Exporter/
See https://discord.com/channels/937901803608096828/1027831463103696928/1325627562080206878
Changed a heading to _Bank Export and Importers_ as this is more correct given the kind of contributions we see here.
Also, did I move the _My Edenred_ entry to its proper alphabetical place.
=> Community repos ICS Cards and Amazon Order CVS file generators.

docs/accounts/index.md
> Off budget accounts don't effect the budget and are meant to track stuff like investments and mortgages. Transactions in off budget accounts can't be categorized; they simply track balances over time.
Should be `affect`, a verb, instead of `effect`, a noun.
=> [WIP] docs: changed effect (noun) to affect (verb)

docs/advanced/http-header-auth.md, docs/config/index.md
This is to go along with https://github.com/actualbudget/actual-server/pull/499 and should be merged until after that PR
This adds the new config options to the docs for the Auth proxy specific setting.
=> Add auth proxies config to the docs

blog/2025-02-06-release-25-2-1.md, docs/releases.md
What commits will be included in the release?
https://github.com/actualbudget/actual/compare/v25.2.1?expand=1
---
- web: https://github.com/actualbudget/actual/pull/4319
- server: https://github.com/actualbudget/actual-server/pull/565
- docs: https://github.com/actualbudget/docs/pull/628
=> 🔖 (25.2.1) fix desktop apps and reports page

docs-sidebar.js, docs/actual-server-repo-move.md
Documenting the repo move. I'll attach this doc to the Server readme so people are more informed
https://deploy-preview-629.www.actualbudget.org/docs/actual-server-repo-move
=> Documenting the repo move

docs/install/local.md
s/below/above/ referring to the startup output (which is now actually "above" the paragraph)
=> Small doc correction to local.md install instructions

docs/actual-server-repo-move.md, docs/config/https.md, docs/config/index.md, docs/experimental/oauth-auth.md
Making it clearer where the config.json file lives and adding it to the repo move instructions.
=> Update sync server config information

.github/actions/spelling/expect.txt, blog/2025-03-01-release-25-3-0.md, docs/releases.md
Release docs for https://github.com/actualbudget/actual/pull/4478
=> 🔖 (25.3.0)

docs/actual-server-repo-move.md, docs/install/docker.md
Updating to point to the new github container located here: https://ghcr.io/actualbudget/actual
This is to accommodate this change: https://github.com/actualbudget/actual/pull/4483
=> Update github container reference to new repo

docs/install/local.md
Missed an instance of ```yarn start:server```
=> Update missing start server command

docs/install/index.md
I created a repository with steps to deploy Actual Budget as a Cloud Run service. I believe this is a better way to deploy in GCP and it's less complicated.
=> add gcp cloud run install option

docs/actual-server-repo-move.md, docs/contributing/project-details/index.md, docs/contributing/releasing.md, docs/contributing/windows.md, docs/install/local.md
Should be merged with: https://github.com/actualbudget/actual/pull/4569
**Changed pages:** 
- https://deploy-preview-661.www.actualbudget.org/docs/install/local
- https://deploy-preview-661.www.actualbudget.org/docs/contributing/project-details/
- https://deploy-preview-661.www.actualbudget.org/docs/contributing/releasing/
- https://deploy-preview-661.www.actualbudget.org/docs/contributing/windows/
- https://deploy-preview-661.www.actualbudget.org/docs/actual-server-repo-move/
=> Update docs with new instructions for workspace reference in server

docs-sidebar.js, docs/actual-server-repo-move.md, docs/config/https.md, docs/config/index.md, docs/getting-started/roadmap-for-new-users.md, docs/install/build-from-source.md, docs/install/index.md, docs/install/local.md, src/pages/download.md
- Added desktop app to installation options "on your own machine" 
- For building from source
- Windows Users will need Git Bash so that they can build the web client using the bash scripts.
- Added a warning on the build from source page
- Reordered the _Build from source_ link to the bottom to encourage the simpler options insted
=> Adding git bash as a prereq for Windows & renaming local install to Build from source

docs/contributing/index.md
Referenced script is introduced here https://github.com/actualbudget/actual/pull/4664
=> Update documentation to include new yarn generate:release-notes script

docs/actual-server-repo-move.md
It should help people moving to the new repo on Windows:
Based on this:
https://discord.com/channels/937901803608096828/1355224207541276826/1355229374986719242
=> Updating repo move instructions to include bash requirement

docs/advanced/bank-sync/gocardless.md
Hi!
I asked GoCardless support to have more informations about the free tier. They told me that the 50 connections (techincally **requisitions**) per month are actually the "initial" connections to the bank. 
Then you have a limit of 4 sync for each bank every day. There's no a monthly limit for syncing.
I have 3 banks linked in actual budget and this was their answer:
>Yes, can confirm that it would be 3 out of your 50 available requisitions monthly. 
As for the amount of times you can sync transactions daily - there's a limit by banks where it's 4 calls for transactions per 24 hours per account_id. Same goes for account details and balances - 4 requests for each in a 24 hour period for each account_id. There is no monthly limit though, just the daily one. This is explained in more …
=> [WIP] free tier clarification in gocardless.md

src/pages/download.md
- Closes #681
Adds Intel and Apple Silicon to the relevant macOS downloads.
=> [WIP] downloads: intel and apple silicon mac labels [#681]

docs-sidebar.js, docs/config/index.md, docs/contributing/releasing.md, docs/install/cli-tool.md, docs/install/index.md
**To be merged on the next release.**
Goes with the new @actual-app/sync-server package: https://github.com/actualbudget/actual/pull/4798
**Pages changed:**
- https://deploy-preview-680.www.actualbudget.org/docs/install/
- https://deploy-preview-680.www.actualbudget.org/docs/install/cli-tool
- https://deploy-preview-680.www.actualbudget.org/docs/contributing/releasing
- https://deploy-preview-680.www.actualbudget.org/docs/config
**Notable changes**
- New CLI Tool docs
- Cutting a release - we no longer need to manually publish any npm packages.
=> Docs for new sync-server npm package

docs/config/reverse-proxies.md
Changes made with some justification, in order of commits:
- removed port mapping for `actual-server` service since we're using Caddy as the reverse proxy, similar to how there's no port mapping for the Traefik example
- minor consistency changes by referring to the Traefik example:
- moved `image: caddy:alpine` to the top
- add restart policy
- swapped one inconsistent single-quoted port mapping to double quotes
=> [WIP] Minor tweaks to the Caddy compose file

docs/config/reverse-proxies.md, docs/install/build-from-source.md
I think this might be useful for people running the Actual Desktop app with the sync server. 
I might add the link to this in the desktop app dedicated docs page (when I've made it). In that page, I'll mention that a reverse proxy can expose Actual Server to the internet for free.
- https://deploy-preview-688.www.actualbudget.org/docs/config/reverse-proxies
- https://deploy-preview-688.www.actualbudget.org/docs/install/build-from-source
=> Ngrok reverse proxy docs

docs/contributing/windows.md, docs/install/build-from-source.md
I think I got all instances where we specify a version, there seem to only be two places in the docs.
We'll also call it out in the release notes.
https://github.com/actualbudget/actual/pull/4978
=> change minimum version of Node.js to version 20

docs/config/reverse-proxies.md
Also changed the proxy pass to be http instead of https since the default for an Actual container is http.
=> Fixed Typo on apache reverse proxy page

docs/experimental/goal-templates.md
The last two examples for the goals have created confusion because the template and goals line shows in one line:
https://discord.com/channels/937901803608096828/1372691110614274170/1376211790639136779
This PR makes sure that any `#template` and `#goal` lines that are meant to go together are displayed on top of each other instead of inline.
It also makes sure that all uses of `#template` show with inline code-formatting for overall conistency.
(Let me know if you'd rather have this in a separate PR and I'll splice out that commit.)
=> Fix ambiguous examples in goal-templates page

docs/install/index.md
Add a link to [my guide](https://adamu.jp/blog/actual_budget_nas) to installing Actual on a Synology NAS that uses a different method than the existing guide: using Docker's [Container Manager](https://kb.synology.com/DSM/help/ContainerManager/docker_desc?version=7) app, and additional TLS certificate options.
=> add an alternative Synology guide

docs/community-repos.md
Current documentation includes ActualTap-Py which is a fork of https://github.com/MattFaz/actualtap *(which I use/maintain)*.
Adding in the original ActualTap repo and updating ActualTap-Py to clarify differences.
=> [WIP] ActualTap documentation

.github/actions/spelling/expect.txt, docs-sidebar.js, docs/contributing/leadership/cursor-ide.md, docs/contributing/leadership/new-core-contributors-guide.md
- Introduced a new document for Cursor IDE, detailing setup, automation, and custom rules.
- Updated the new core contributors guide to include a link to the Cursor IDE documentation for additional tips.
=> Add Cursor IDE documentation

docs/index.md
Hi, this is my first time contributing to an open-source project.
I noticed a small typo in the documentation (a missing period at the end of a sentence), and I’ve submitted a fix for it.
Please feel free to suggest any improvements if I’ve done anything incorrectly. Thank you for maintaining this project!
=> [WIP] Fixing a typo in the documentation

docs/getting-started/tips-tricks.md
Prevented `cmd` mod from getting changed to `ctrl` when users were not on Macs.
=> Fix ctrl/cmd issue on tips and tricks page

docs/advanced/bank-sync/gocardless.md
I encountered this issue when I [created a PR](https://github.com/actualbudget/actual/pull/5479) to add a new bank to Actual. 
The docs were instructing me to first create the PR and then generate the docs. 
At the same time, when I tried to open the PR, the default template message was instructing me to generate the release notes *before* opening the PR. 
```
```
I am not sure who is telling the truth here, but given the emphasis that the template put on *before* I am inferring that the docs had the wrong order. If this is not the case, of course feel free to nuke this PR and update the GitHub template instead.
=> [WIP] Adding bank: fixed instructions order

docs/experimental/rule-templating.md
I was confused at first and was thinking of "substitute". So I thought it might be a nice addition to the docs.
Additionally I cleaned up the markdown tables a bit and added a link to the patterns available for date `format`
=> rule-templating: clarify meaning of sub prefix in date functions

.github/actions/spelling/expect.txt, blog/2025-10-01-release-25-10-0.md, blog/2025-10-02-release-25-10-0.md, docs/releases.md
Actual: https://github.com/actualbudget/actual/pull/5834
Docs: https://github.com/actualbudget/docs/pull/806
=> 🔖 (25.10.0)
